version: "3.8"

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fire-drupal
    ports:
      - "8085:80"  # Access Drupal at http://localhost:8085
    restart: always
    environment:
      - DRUPAL_DB_HOST=mariadb
      - DRUPAL_DB_NAME=fire-safety
      - DRUPAL_DB_USER=admin
      - DRUPAL_DB_PASSWORD=9shZv^XZ/8_pR0eNV|
    depends_on:
      - mariadb
    volumes:
      - drupal_data:/var/www/html/web/sites/default/files

  mariadb:
    image: mariadb:10.11
    container_name: fire-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=fire-safety
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=9shZv^XZ/8_pR0eNV|
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz:ro # Optional: initial import

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # ← This line is the fix
    restart: always
    ports:
      - "8086:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=512M
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=300
    depends_on:
      - mariadb

volumes:
  drupal_data:
  mariadb_data:
